version: '3'

services:
  palmaf:
    build:
      context: .
      dockerfile: Dockerfile 
    env_file: .env
    networks:
      - entrypoint
    ports:
      - 8000:8000
    volumes:
      - ./data:/app/data
    restart: always

networks:
  entrypoint:
    name: entrypoint
    external: true