# Generated by Django 5.1.7 on 2025-03-20 14:09

import django.db.models.deletion
import django.utils.timezone
import prose.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', prose.fields.DocumentContentField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='thumbnail_caption',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=prose.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_update_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='post_update_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='post',
            name='version',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comments', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='content_body',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.articlecontent'),
            preserve_default=False,
        ),
    ]
