# Generated by Django 5.1.7 on 2025-03-20 14:53

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articlecontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_body',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_caption',
            field=martor.models.MartorField(),
        ),
        migrations.DeleteModel(
            name='ArticleContent',
        ),
    ]
