# Generated by Django 5.1.7 on 2025-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_content_body_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
